### ISSUE TITLE
Integration tests failing in Pangeo environments

### ISSUE THREAD

**Issue by szwiep** [ec-jrc/nrt#14]
The integration tests are failing on `xr.open_dataset` calls when I'm using a Pangeo docker image in JupyterHub (2024.07.08):
```
>       raise ValueError(error_msg)
E       ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'argo', 'cfgrib', 'gini', 'kerchunk', 'pydap', 'rasterio', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
E       https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
E       https://docs.xarray.dev/en/stable/user-guide/io.html
```
However, I don't run into any errors when running tests locally on a Windows 11 machine. For both systems, I was running `pytest` from the top level directory of the repo.

It's possible I'm not following the correct testing procedure for your repo, so addressing #13 first might resolve this!

**Comment by loicdtx** [comment]
@szwiep thanks for reporting this. Is this what you tried?

```bash
# Enter container in interactive mode
docker run --rm -it pangeo/pangeo-notebook:latest /bin/bash
# Within container
git clone https://github.com/ec-jrc/nrt.git
cd nrt
pip install -e .[tests]
pytest
```

I confirm that this results in a failure of the integration tests. The reason is that the image does not include the `git lfs` extension which is used to version binary files accessible through the `nrt.data` module and used in these integration tests.

The following sequence of commands works.

```bash
# Enter container as root
docker run --rm -it --user root pangeo/pangeo-notebook:latest /bin/bash
apt update
apt install git-lfs
git lfs install
git clone https://github.com/ec-jrc/nrt.git
cd nrt
pip install -e .[tests]
pytest
```

I'll add a note about git lfs in the CONTRIBUTING.md. Thanks

**Comment by szwiep** [comment]
The `git lfs` solution works for me. Thanks for getting to the bottom of this!
