### ISSUE TITLE
Update MANIFEST.in

### ISSUE THREAD

**Issue by AdamRJensen** [ec-jrc/nrt#24]
https://github.com/ec-jrc/nrt/blob/9348c584f0cd6f89fbe575ce969430725ddf4947/MANIFEST.in#L1-L7

I don't think you need to exclude the manifest file.

Also why are you including the readme file?

**Comment by loicdtx** [comment]
Thanks @AdamRJensen. Excluding MANIFEST.in isn't strictly necessary, but not uncommon since it's not required in the distribution. For [rasterio](https://github.com/rasterio/rasterio/blob/main/MANIFEST.in#L13) for example. I don't have a strong preference either way and prefer to maintain the current approach.

The README.rst on the other hand must be included as it serves as the long_description for the package, which is displayed on the PyPI landing page. (See [example](https://github.com/ec-jrc/nrt/blob/master/setup.py#L32)).
